### ISSUE TITLE
`python setup.py iOS` seems to be grabbing wrong version of toga-ios

### ISSUE THREAD

**Issue by phildini** [pybee/briefcase#14] opened 2016-07-22 14:39 UTC
Not sure if this should be logged here or against toga, but when you specify, say:

`'toga[iOS]>=0.2.0.dev1'`

you get `toga 0.2.0.dev1` but `toga-ios 0.1.2`.

**Comment by marcmolla** [comment] 2016-09-15 19:58
I get toga 0.2.0 and, as this version does not provides [ios], it automatically install toga-cocoa.

I have to use 'toga[ios]==0.2.0.dev1' instead.

**Comment by freakboy3742** [comment] 2016-09-16 02:30
AFAIK, this *should* have been addressed by the 0.2.0 release. @phildini's patch predates that release; I can't reproduce what you're describing with the current releases on PyPI: 
```
(testbed3)hammer:tutorial2 rkm$ pip install toga[iOS]
Collecting toga[iOS]
  Using cached toga-0.2.0-py2.py3-none-any.whl
  toga 0.2.0 does not provide the extra 'iOS'
Collecting toga-cocoa; sys_platform == "darwin" (from toga[iOS])
  Using cached toga_cocoa-0.2.0-py2.py3-none-any.whl
Collecting rubicon-objc (from toga-cocoa; sys_platform == "darwin"->toga[iOS])
  Using cached rubicon_objc-0.2.2-py2.py3-none-any.whl
Collecting toga-core (from toga-cocoa; sys_platform == "darwin"->toga[iOS])
  Using cached toga_core-0.2.0-py2.py3-none-any.whl
Collecting colosseum (from toga-core->toga-cocoa; sys_platform == "darwin"->toga[iOS])
  Using cached colosseum-0.1.2-py2.py3-none-any.whl
Installing collected packages: rubicon-objc, colosseum, toga-core, toga-cocoa, toga
Successfully installed colosseum-0.1.2 rubicon-objc-0.2.2 toga-0.2.0 toga-cocoa-0.2.0 toga-core-0.2.0
```

Can you provide a reproduction case?

**Comment by freakboy3742** [comment] 2016-09-16 02:40
Ah - sorry - now I read *all* of your report, I see the problem :-)

This is effectively a documentation problem for a subtle change in how Toga is installed. `toga[iOS]` is no longer a meaningful target; you either install:

* `toga-ios` if you want Toga for iOS and it's dependencies, or
* `toga` if you want Toga for your current platform.

If you can point me at the documentation that led you down the wrong path, that is what needs to be corrected (or if you want, a PR for a fix to those docs would be fantastic!)

This change had to be made because of the difference between the development platform and the deployment platform when dealing with mobile. The setup.py configuration for `toga` attempts to auto detect the "current" platform - which is wherever setup.py is running, not the platform that setup.py is running *for*. So, as a result, you end up accidentally installing toga-cocoa whenever you are writing for iOS.

Ideally, I'd *like* to re-enable the toga[iOS] option, or be able to specify a "deployment platform" in setup.py that setup.py will honour (so that `python setup.py ios` will install toga-ios just by putting toga in `install_requires`). However, it isn't clear to me that this is possible without modifications to setuptools/distutils.

**Comment by marcmolla** [comment] 2016-09-16 11:12
The README.rst is the document to update. I included a proposal in a PR that I sent with a couple of basic tutorials:
https://github.com/pybee/briefcase/pull/16

**Comment by freakboy3742** [comment] 2016-09-17 02:41
Closing due to merge of #16.

**Closed by freakboy3742** 2016-09-17 02:41 UTC
