### ISSUE TITLE
Flask Support

### ISSUE THREAD

**Issue by infosisio** [pybee/briefcase#163] opened 2018-08-27 20:22 UTC
I am a huge fan of this project.

I primarily use Flask however instead of Django and would like to port some existing applications easily.

Any chance of this happening any time soon ?

Thanks !

**Comment by Tadaboody** [comment] 2018-08-27 20:29
Possible duplicate of #35

**Comment by meichthys** [comment] 2018-08-27 20:43
@infosisio  Could you close this issue for now so we can keep the discussion on a single issue?

**Closed** 2018-08-27 21:04 UTC
